### PR TITLE
Fix audio over bluetooth

### PR DESCRIPTION
**Pull request by Dinolek**

### CODE REVIEW

**Review by SscSPs — COMMENTED** [review]
This works for RN2?

**Comment by Dinolek** [comment]
This is first made for rn2
https://github.com/HermesRepos/android_device_xiaomi_hermes/commit/924d2019119a01d28b75d7049336e7bafcda8879

**Comment by imrankadd** [comment]
When will comera fix, and fp still not working by restore method

**Comment by imrankadd** [comment]
Data speed always shows 0 Kbps, please solve it. I have only tested RR 5.8.2

**Comment by WisniaPL** [comment]
Ok, thanks Dinolek. @imrankadd  Fp working by restore method

**Comment by ZeNiX74** [comment]
Audio over BT is working fine

**Pull request merged**
