### PR TITLE
renamed LoopMobile to Reliance Jio

### PR DESCRIPTION
**Pull request by SscSPs**
This is done to resolve a little issue where Reliance Jio Network would be displayed as Loop Mobile

### CODE REVIEW

**Comment by SscSPs** [comment]
As per Wikipedia, LoopMobile is dead.
image

Ceased operations: November 29, 2014

**Comment by SscSPs** [comment]
https://en.wikipedia.org/wiki/Loop_Mobile

**Comment by SscSPs** [comment]
ok, this is not yet done.
will open it when its done.

**Comment by SscSPs** [comment]
Done, merge this

**Comment by imrankadd** [comment]
Will it in los 14.1 by WisniaPL sir? Or this will a new rom?

**Comment by WisniaPL** [comment]
ok, thanks ;)

**Pull request merged**
