### PR TITLE
fix audio over bluetooth

### PR DESCRIPTION
**Pull request by SscSPs**
used dinolek's method to try to fix audio over bluetooth issue

### CODE REVIEW

**Comment by SscSPs** [comment]
and added TapToWake for dt2w.

**Comment by imrankadd** [comment]
Bro please add VoLTE in this ROM please

**Comment by WisniaPL** [comment]
@SscSPs it works?

**Comment by SscSPs** [comment]
I am facing some issues. 
i am unable to build 
photo6215015121709803434 1

**Comment by WisniaPL** [comment]
Please use prebuilt kernel

**Comment by SscSPs** [comment]
I am using prebuild now to test the audio over bluetooth. 
will reply as i test it.
and i also want to test dt2w, so i'll have to modify a bit of kernel...

**Comment by WisniaPL** [comment]
ok

**Pull request closed without merging**
